import { faviconIcons } from "@skillsync/utils/faviconIcons";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import type { Metadata } from "next";
import { getPlanById } from "../queries/getPlanById";

export const metadata: Metadata = {
  title: "SkillSync",
  description: "Generated by create next app",
  icons: faviconIcons,
};

export default async function Layout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ id: string }>;
}>) {
  const { id } = await params;
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["plan", { id: id }],
    queryFn: () => getPlanById({ planId: id }),
  });

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      {children}
    </HydrationBoundary>
  );
}
