import { faviconIcons } from "@skillsync/utils/faviconIcons";
import type { Metadata } from "next";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { getLearningPath } from "../queries/getLearningPath";

export const metadata: Metadata = {
  title: "SkillSync",
  description: "Generated by create next app",
  icons: faviconIcons,
};

export default async function Layout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ pathId: string }>;
}>) {
  const { pathId } = await params;
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["learningPath", { id: pathId }],
    queryFn: () => getLearningPath({ id: pathId }),
  });

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      {children}
    </HydrationBoundary>
  );
}
