import { Navbar } from "@skillsync/components/Navbar";
import { faviconIcons } from "@skillsync/utils/faviconIcons";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryClientProvider } from "./providers/ReactQueryClientProvider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SkillSync",
  description: "Generated by create next app",
  icons: faviconIcons,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased w-[100%] max-w-7xl mx-auto px-4`}>
        <ClerkProvider>
          <ReactQueryClientProvider>
            <Navbar />
            {children}
          </ReactQueryClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
